"""add location_area to complaints

Revision ID: d73556bc9954
Revises: 
Create Date: 2026-05-06 22:19:43.057331

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd73556bc9954'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('complaints', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location_area', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('dispatch_reason', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('ai_processed_complaint', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('possible_duplicate_complaint_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('admin_comment', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('date_resolved', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('complaints', schema=None) as batch_op:
        batch_op.drop_column('date_resolved')
        batch_op.drop_column('updated_at')
        batch_op.drop_column('admin_comment')
        batch_op.drop_column('possible_duplicate_complaint_id')
        batch_op.drop_column('ai_processed_complaint')
        batch_op.drop_column('dispatch_reason')
        batch_op.drop_column('location_area')

    # ### end Alembic commands ###
