import type { Complaint, User, MonthlyReport } from "./types";

// --- Mock users ---------------------------------------------------------------

export const MOCK_CITIZEN: User = {
  id: "1",
  username: "juandelacruz",
  email_address: "juan@example.com",
  location_assigned: "Purok 3, Brgy. San Isidro",
  role: "citizen",
};

export const MOCK_ADMIN: User = {
  id: "2",
  username: "admin1",
  email_address: "admin1@alalai.brgy",
  location_assigned: "Barangay Hall, Brgy. San Isidro",
  role: "admin",
};

// --- Mock complaints ----------------------------------------------------------

export const MOCK_COMPLAINTS: Complaint[] = [
  {
    id: "2341",
    user_id: "1",
    citizenName: "Juan dela Cruz",
    email_address: "juan@example.com",
    title: "Broken streetlight near Purok 3",
    tagging: "Infrastructure",
    location: "Purok 3, near the basketball court, Brgy. San Isidro",
    lat: 14.5991,
    lng: 120.9828,
    description:
      "The streetlight at the corner of Purok 3 near the basketball court has been broken for over two weeks. Residents are unable to walk safely at night.",
    status: "in-progress",
    priority: "high",
    media:
      "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&q=80",
    created_at: "2026-04-30T08:00:00Z",
    updated_at: "2026-05-01T10:00:00Z",
    assigned: 2,
    adminName: "Admin 1",
    adminComment:
      "This report is now ongoing but may take more than 2 days due to procurement of replacement parts.",
    adminCommentDate: "2026-05-01",
  },
  {
    id: "2198",
    user_id: "1",
    citizenName: "Juan dela Cruz",
    email_address: "juan@example.com",
    title: "Illegal dumping beside the canal",
    tagging: "Environment",
    location: "Near Canal A, Purok 1, Brgy. San Isidro",
    lat: 14.6008,
    lng: 120.9824,
    description:
      "Large pile of garbage illegally dumped beside the main canal causing foul odor and drainage blockage risk.",
    status: "for-review",
    priority: "medium",
    created_at: "2026-04-22T09:00:00Z",
    updated_at: "2026-04-25T14:00:00Z",
    assigned: 2,
    adminName: "Admin 1",
    adminComment: "Issue has been addressed. Please confirm and close.",
    adminCommentDate: "2026-04-25",
  },
  {
    id: "2087",
    user_id: "1",
    citizenName: "Juan dela Cruz",
    email_address: "juan@example.com",
    title: "Stray dogs in the playground",
    tagging: "Public Safety",
    location: "Barangay Playground, Brgy. San Isidro",
    lat: 14.5975,
    lng: 120.9836,
    description:
      "Multiple stray dogs spotted in the playground, posing a risk to children. Some appear aggressive.",
    status: "pending",
    priority: "high",
    created_at: "2026-04-18T07:30:00Z",
    updated_at: "2026-04-18T07:30:00Z",
  },
  {
    id: "2412",
    user_id: "1",
    citizenName: "Juan dela Cruz",
    email_address: "juan@example.com",
    title: "Flooded drainage near Purok 5",
    tagging: "Flooding",
    location: "Purok 5, main road, Brgy. San Isidro",
    lat: 14.5984,
    lng: 120.9854,
    description:
      "The drainage along Purok 5 has been clogged and overflows during rain, flooding the main road.",
    status: "in-progress",
    priority: "medium",
    created_at: "2026-05-03T11:00:00Z",
    updated_at: "2026-05-04T08:00:00Z",
    assigned: 2,
    adminName: "Admin 1",
    adminComment:
      "We are currently assessing the extent of the drainage blockage before dispatching a team.",
    adminCommentDate: "2026-05-04",
  },
  {
    id: "2500",
    user_id: "1",
    citizenName: "Juan dela Cruz",
    email_address: "juan@example.com",
    title: "Resolved canal issue",
    tagging: "Environment",
    location: "Canal B, Purok 2, Brgy. San Isidro",
    lat: 14.6001,
    lng: 120.984,
    description: "Canal was cleaned and unclogged.",
    status: "resolved",
    priority: "low",
    created_at: "2026-04-10T08:00:00Z",
    updated_at: "2026-04-15T12:00:00Z",
    date_resolved: "2026-04-15T12:00:00Z",
    assigned: 2,
    adminName: "Admin 1",
    adminComment: "Canal cleaned. Resolved.",
    adminCommentDate: "2026-04-15",
  },
];

// --- Admin assigned complaints (superset) ------------------------------------

export const MOCK_ADMIN_COMPLAINTS: Complaint[] = [
  ...MOCK_COMPLAINTS,
  {
    id: "5698",
    user_id: "3",
    citizenName: "Maria Santos",
    email_address: "maria@example.com",
    title: "Illegal dumping on Maharlika St.",
    tagging: "Environment",
    location: "Maharlika St., Brgy. San Isidro",
    lat: 14.5997,
    lng: 120.9862,
    description: "Residents dumping trash directly on the street.",
    status: "pending",
    priority: "medium",
    media:
      "https://images.unsplash.com/photo-1530587191325-3db32d826c18?w=800&q=80",
    created_at: "2026-05-01T06:00:00Z",
    updated_at: "2026-05-01T06:00:00Z",
    assigned: 2,
    adminName: "Admin 1",
  },
  {
    id: "2152",
    user_id: "4",
    citizenName: "Pedro Reyes",
    email_address: "pedro@example.com",
    title: "Pothole causing accidents",
    tagging: "Infrastructure",
    location: "Near market, Brgy. San Isidro",
    lat: 14.5963,
    lng: 120.9845,
    description: "Large pothole causing vehicle damage and accidents.",
    status: "for-review",
    priority: "high",
    created_at: "2026-04-25T08:00:00Z",
    updated_at: "2026-04-28T12:00:00Z",
    assigned: 2,
    adminName: "Admin 1",
    adminComment: "Road has been repaired. Please confirm and close.",
    adminCommentDate: "2026-04-28",
  },
  {
    id: "2610",
    user_id: "5",
    citizenName: "Ana Reyes",
    email_address: "ana@example.com",
    title: "Noise complaint near chapel",
    tagging: "Noise Complaint",
    location: "Near Chapel, Brgy. San Isidro",
    lat: 14.597,
    lng: 120.985,
    description: "Loud music being played past 10pm regularly.",
    status: "resolved",
    priority: "low",
    created_at: "2026-04-20T20:00:00Z",
    updated_at: "2026-04-22T10:00:00Z",
    date_resolved: "2026-04-22T10:00:00Z",
    assigned: 2,
    adminName: "Admin 1",
    adminComment: "Warning issued to establishment. Resolved.",
    adminCommentDate: "2026-04-22",
  },
];

// --- Mock monthly report (AI-generated) --------------------------------------

export const MOCK_MONTHLY_REPORT: MonthlyReport = {
  id: "1",
  month: "2026-04-01T00:00:00Z",
  overall_complaint_count: 10,
  overall_completion_rate: 70,
  forecast: "Increase in infrastructure complaints expected in May.",
  suggest_actions:
    "Prioritize road repair teams; schedule canal cleanup for Purok 1.",
  avg_solution_days: 4.2,
  category_breakdown: {
    Infrastructure: 3,
    Environment: 3,
    Flooding: 1,
    "Public Safety": 1,
    "Noise Complaint": 1,
    Other: 1,
  },
  created_at: "2026-05-01T00:00:00Z",
};
